import React, { useState, useMemo, useEffect, useRef, useCallback } from "react";
import { hl } from "./ui";
import { field } from "./modal";
import { clean, headline, glass } from "./studio";
import { matches } from "./analysis.js";


const LOGO_SRC = import.meta.env.BASE_URL + "logo.png";

const CATEGORIES = ["All", "Beauty & Skincare", "Fashion", "Electronics", "Local Services", "Supplements", "Food & Bev", "Travel", "Sport & Fitness", "Home & Decor", "Fragrances"];

/* Each template carries its own CSS-built ad creative (art). No external media. */
const TEMPLATES = [
  {
    id: "myth-fact", type: "static", trending: true,
    category: "Beauty & Skincare", label: "Beauty & Cosmetics", title: "Myth vs Fact Debunk",
    format: "4:5 · Static · Myth and fact split", framework: "Contrarian angle",
    art: { kind: "myth", bg: "linear-gradient(155deg,#0f172a 0%,#1e293b 100%)", hl: "#7dd3fc", hook: "*Myth* vs. *Fact*", myth: "More steps means clearer skin", fact: "The right 2 beat any 5", tag: "Skincare" },
    why: [
      "Stating a myth the viewer already believes stops the scroll, then the fact contradicts it in the same frame.",
      "The split layout gives two clear zones, so the contrast is understood in one second.",
      "The fact half doubles as the product mechanism, so the pitch never feels bolted on.",
    ],
    headline: "Your SPF isn't the problem",
    primary: "Myth: you need 5 products for clear skin. Fact: you need the right 2. Here's the routine our customers switched to.",
  },
  {
    id: "controller-demo", type: "static", trending: true,
    category: "Electronics", label: "Electronics", title: "Game Controller Demo",
    format: "4:5 · Static · Macro hands-on product shot", framework: "Show, don't tell",
    art: { kind: "stat", bg: "linear-gradient(160deg,#1e1b4b 0%,#0f172a 100%)", hl: "#a5b4fc", hook: "*Zero* stick drift", big: "0", unit: "drift after 400 hours", chips: ["Hall-effect sticks", "Back paddles", "PC · Switch"], tag: "Controller" },
    why: [
      "A close-up of hands on the product shows what it feels like before the viewer asks.",
      "One bold number as the headline carries the claim without any reading effort.",
      "Tight framing keeps the product and the claim inside the safe area on every placement.",
    ],
    headline: "Zero drift. Tested for 400 hours.",
    primary: "Hall-effect sticks that don't drift. Swap-in back paddles. Plug in and play on PC, Switch and mobile.",
  },
  {
    id: "split-proof", type: "static", trending: false,
    category: "Beauty & Skincare", label: "Beauty & Cosmetics", title: "Split-Screen Proof",
    format: "4:5 · Static · Before / after split", framework: "Comparison",
    art: { kind: "split", bg: "linear-gradient(160deg,#172554 0%,#0f172a 100%)", hl: "#93c5fd", hook: "Same face. *28 days.*", left: { label: "Day 1", metric: "14", note: "breakouts" }, right: { label: "Day 28", metric: "3", note: "breakouts" }, tag: "Skincare" },
    why: [
      "Two panels let the eye find the difference in under a second, with no copy needed.",
      "Proof sits in the image itself, so the headline can go straight to the offer.",
      "Works in feed and Stories with one crop, which keeps production cheap to iterate.",
    ],
    headline: "Day 1 vs Day 28",
    primary: "Same lighting. Same camera. Four weeks of one serum. See the full results from real customers.",
  },
  {
    id: "texture-asmr", type: "static", trending: false,
    category: "Beauty & Skincare", label: "Skincare", title: "Texture Close-Up",
    format: "4:5 · Static · Macro texture close-up", framework: "Sensory hook",
    art: { kind: "review", bg: "linear-gradient(155deg,#134e4a 0%,#0f172a 100%)", hl: "#5eead4", hook: "STOP scrolling if you have *dry skin*", quote: "Melts in. Never sticky. My skin finally stopped feeling tight by 3pm.", who: "Verified buyer", initial: "M", tag: "Skincare" },
    why: [
      "A macro texture shot triggers a tactile reaction that holds attention without any motion.",
      "One short benefit line keeps the frame clean and the image the hero.",
      "Works for any product with a visible texture: creams, sauces, fabrics, powders.",
    ],
    headline: "Melts in. Never sticky.",
    primary: "A barrier cream that sinks in in 10 seconds. No white cast, no greasy finish. Dermatologist tested.",
  },
  {
    id: "offer-lookbook", type: "static", trending: false,
    category: "Fashion", label: "Fashion", title: "Offer Stack Lookbook",
    format: "4:5 · Static · Editorial + offer bar", framework: "Outcome + urgency",
    art: { kind: "offer", bg: "linear-gradient(155deg,#4c1d3a 0%,#0f172a 100%)", hl: "#fda4af", hook: "The *fall edit*", big: "20%", sub: "off this week", pills: ["Free returns", "60 days"], cta: "Shop the edit", tag: "Fashion" },
    why: [
      "Editorial imagery earns the stop; the offer bar converts the attention into a click.",
      "Stacking the offer (discount plus free returns) removes the two biggest checkout objections.",
      "A single look keeps the eye on one product instead of splitting focus.",
    ],
    headline: "The fall edit — 20% off this week",
    primary: "Tailored pieces you'll wear to work and dinner. Free returns for 60 days, so ordering two sizes costs you nothing.",
  },
  {
    id: "tryon-haul", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Try-On Haul Hook",
    format: "4:5 · Static · Mirror selfie try-on", framework: "Social proof",
    art: { kind: "steps", bg: "linear-gradient(160deg,#3b0764 0%,#0f172a 100%)", hl: "#e9d5ff", hook: "I tried on *7 pieces*", rows: [["Wool coat", "keep"], ["Satin skirt", "return"], ["Knit set", "keep"], ["Wide jeans", "keep"]], foot: "3 are staying", tag: "Fashion" },
    why: [
      "A mirror selfie borrows the most familiar organic photo format on Instagram.",
      "The rack in the background hints at choice, which makes people want to see more.",
      "A specific number in the headline ('7 pieces') makes the post feel real and honest.",
    ],
    headline: "I tried on 7 pieces. 3 are staying.",
    primary: "An honest try-on of the new drop: what fits true to size, what runs small, and the one I'm buying twice.",
  },
  {
    id: "us-vs-them", type: "static", trending: false,
    category: "Electronics", label: "Electronics", title: "Us vs Them Spec Table",
    format: "1:1 / 4:5 · Static · Comparison grid", framework: "Comparison",
    art: { kind: "compare", bg: "linear-gradient(160deg,#0c4a6e 0%,#0f172a 100%)", hl: "#7dd3fc", hook: "Half the price. *Twice* the battery.", cols: ["You", "Them"], rows: [["Battery", "14 days", "18 hrs"], ["Water rating", "5 ATM", "IP67"], ["Price", "$89", "$179"]], tag: "Smartwatch" },
    why: [
      "Check-versus-cross grids are scanned in under two seconds, even by solution-aware buyers.",
      "Naming the category leader lets your product borrow its awareness.",
      "Converts best when every row is a spec buyers already compare.",
    ],
    headline: "Half the price. Twice the battery.",
    primary: "Same sensors as the leading smartwatch. 14-day battery instead of 18 hours. Compare them side by side.",
  },
  {
    id: "founder-note", type: "static", trending: false,
    category: "Supplements", label: "Supplements", title: "Founder Note Authority",
    format: "4:5 · Static · Product + handwritten note", framework: "Authority",
    art: { kind: "quote", bg: "linear-gradient(155deg,#064e3b 0%,#0f172a 100%)", hl: "#6ee7b7", hook: "A note from the *founder*", text: "I made the magnesium I couldn't find. Three forms, no fillers, tested every batch.", sign: "Founder", tag: "Magnesium" },
    why: [
      "A first-person note from the founder reads as a letter, not an ad.",
      "Explains the why-we-made-this story that supplement buyers use to judge trust.",
      "Keeps claims specific and sourced, which also keeps the ad compliant.",
    ],
    headline: "Why I made the magnesium I couldn't find",
    primary: "Three forms of magnesium, no fillers, third-party tested every batch. Here's what's in each capsule and why.",
  },
  {
    id: "pour-shot", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Beverage", title: "Pour Shot Pattern Interrupt",
    format: "4:5 · Static · Frozen pour shot", framework: "Sensory hook",
    art: { kind: "stat", bg: "linear-gradient(160deg,#78350f 0%,#1c1917 100%)", hl: "#fcd34d", hook: "Your *7am* just got better", big: "20", unit: "minutes to your door", chips: ["Single origin", "First order free"], tag: "Coffee" },
    why: [
      "A frozen mid-pour moment has built-in motion, which breaks the scroll in the first glance.",
      "Appetite appeal is visual, so the product does the persuading.",
      "Easy to reshoot with every new flavor or menu item.",
    ],
    headline: "Your 7am just got better",
    primary: "Single-origin espresso, pulled fresh and delivered in 20 minutes. First order ships free.",
  },
  {
    id: "clinic-trust", type: "static", trending: false,
    category: "Local Services", label: "Local Clinic", title: "Local Clinic Trust Builder",
    format: "4:5 · Static · Practitioner portrait", framework: "Authority",
    art: { kind: "checklist", bg: "linear-gradient(160deg,#075985 0%,#0f172a 100%)", hl: "#7dd3fc", hook: "Same-week *dental checkups*", items: ["Full checkup and clean", "One fixed price", "Book online in 60 seconds"], chip: "New patients welcome", tag: "Dental" },
    why: [
      "A real practitioner in a real room answers the first local question: who will treat me?",
      "Naming the area in the headline qualifies the audience before they click.",
      "A same-week booking offer removes the wait that stops most local leads.",
    ],
    headline: "Same-week dental checkups downtown",
    primary: "New patients get a full checkup and clean for a fixed price. Book online in 60 seconds, no phone call needed.",
  },
  {
    id: "mirror-pas", type: "static", trending: false,
    category: "Beauty & Skincare", label: "Beauty & Cosmetics", title: "Mirror Problem-Agitate",
    format: "4:5 · Static · Problem close-up", framework: "Pain point",
    art: { kind: "timeline", bg: "linear-gradient(155deg,#500724 0%,#0f172a 100%)", hl: "#fda4af", hook: "Concealer that *creases by noon*?", points: [["8am", "ok", "Fresh"], ["12pm", "bad", "Creased"]], foot: "Weightless. Stays put.", tag: "Makeup" },
    why: [
      "Opens on a frustration the viewer has lived, which earns instant recognition.",
      "The question headline makes the problem personal before the product appears.",
      "Problem-aware audiences respond to this more than to feature-first creative.",
    ],
    headline: "Tired of concealer that creases by noon?",
    primary: "Our weightless formula stays put for 12 hours. No caking, no touch-ups. Find your shade in 30 seconds.",
  },
  {
    id: "routine-stack", type: "static", trending: false,
    category: "Supplements", label: "Supplements", title: "Routine Stack UGC",
    format: "4:5 · Static · Lifestyle in-use", framework: "Identity",
    art: { kind: "checklist", bg: "linear-gradient(160deg,#3f3f46 0%,#18181b 100%)", hl: "#bef264", hook: "For people who train *4x a week*", items: ["Creatine, 5g", "Electrolytes", "Nothing else"], chip: "Mixes clear", tag: "Stack" },
    why: [
      "Shows the product inside a routine the audience already follows.",
      "Identity framing (built for lifters) filters out low-intent clicks.",
      "Lifestyle context makes a commodity product feel like part of a habit.",
    ],
    headline: "Built for people who train 4x a week",
    primary: "Creatine, electrolytes and nothing else. Mixes clear, tastes clean, fits in your gym bag.",
  },
  {
    id: "hero-product", type: "static", trending: false,
    category: "Fashion", label: "Footwear", title: "Single Hero Product",
    format: "1:1 / 4:5 · Static · Studio packshot", framework: "Outcome",
    art: { kind: "restock", bg: "linear-gradient(155deg,#1d4ed8 0%,#0f172a 100%)", hl: "#bfdbfe", hook: "The runner that *sold out twice*", badge: "Back in stock", sizes: [["7", false], ["8", true], ["9", true], ["10", true], ["11", false]], tag: "Footwear" },
    why: [
      "A single product on a saturated background is the highest-contrast frame in the feed.",
      "Zero distractions means the eye lands on the product and the price.",
      "The easiest template to A/B test: swap the headline, keep the image.",
    ],
    headline: "The runner that sold out twice",
    primary: "Back in stock in every size. Lightweight foam, breathable knit, free exchanges if the fit's off.",
  },
  {
    id: "review-stack", type: "static", trending: false,
    category: "Electronics", label: "Electronics", title: "Review Screenshot Stack",
    format: "4:5 · Static · Product + reviews", framework: "Social proof",
    art: { kind: "reviews", bg: "linear-gradient(160deg,#1e293b 0%,#020617 100%)", hl: "#fde68a", hook: "*4.8 stars* from verified buyers", items: [["Noise cancelling that works on the metro.", "R."], ["Battery lasts my whole work week.", "D."], ["Better than the pair I paid double for.", "S."]], tag: "Headphones" },
    why: [
      "Real review quotes use the buyer's own words, which beat brand copy for trust.",
      "Star ratings are read before the headline, so proof lands first.",
      "Use only verbatim reviews from your store to keep claims honest.",
    ],
    headline: "4.8 stars from verified buyers",
    primary: "Noise cancelling that actually works on the metro. Read what buyers say after 30 days of daily use.",
  },
  {
    id: "ugly-marker", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Beverage", title: "The Ugly Marker Ad",
    format: "4:5 · Static · Handwritten pattern interrupt", framework: "Pattern interrupt",
    art: { kind: "marker", light: true, bg: "linear-gradient(160deg,#fffdf0 0%,#fef3c7 100%)", hl: "#facc15", hook: "Ok so *this* is why it's better", note: "no fillers, ever", tag: "Snacks" },
    why: [
      "A rough, handwritten look reads as a person, not an ad, so the scroll slows.",
      "A yellow highlighter stroke tells the eye which word matters most.",
      "One red arrow points at the single difference you want remembered.",
    ],
    headline: "Ok so this is why it's better",
    primary: "Made with a short list and nothing else. Look at the label, then look at the rest.",
  },
  {
    id: "price-receipt", type: "static", trending: false,
    category: "Food & Bev", label: "Food & Beverage", title: "Competitor Receipt Breakdown",
    format: "4:5 · Static · Checkout receipt", framework: "Price anchoring",
    art: { kind: "receipt", bg: "linear-gradient(160deg,#14532d 0%,#052e16 100%)", hl: "#86efac", hook: "The *real* cost of your daily coffee", rows: [["Coffee shop, 30 days", "$120", "$38"], ["Delivery fees", "$45", "$0"]], totals: ["$165", "$38"], tag: "Coffee" },
    why: [
      "A receipt looks like proof, and shoppers already trust the format.",
      "The crossed-out total sets the anchor before your price appears.",
      "Show only prices you can back up with a real comparison.",
    ],
    headline: "The real cost of your daily coffee",
    primary: "Add it up: the shop, the delivery fees, the impulse extras. Then compare it to one bag a month.",
  },
  {
    id: "tweet-reaction", type: "static", trending: true,
    category: "Beauty & Skincare", label: "Beauty & Cosmetics", title: "Tweet Reaction Screenshot",
    format: "4:5 · Static · Social post screenshot", framework: "Social proof",
    art: { kind: "tweet", bg: "linear-gradient(160deg,#0f172a 0%,#1e3a8a 100%)", hl: "#7dd3fc", hook: "Someone *said it better* than us", text: "did not expect a $30 serum to fix my dry patches. ordering a second one.", name: "Sam", handle: "@skincare_sam", tag: "Skincare" },
    why: [
      "A post from a real customer feels unpaid, which lifts trust.",
      "The familiar card format stops the scroll like a friend's post.",
      "Use only reactions you have permission to share.",
    ],
    headline: "Someone said it better than us",
    primary: "We did not write this. A customer did. Read it, then see what they are talking about.",
  },
  {
    id: "ingredient-dissection", type: "static", trending: false,
    category: "Supplements", label: "Supplements", title: "Ingredients Dissection",
    format: "4:5 · Static · Exploded component view", framework: "Component proof",
    art: { kind: "ingredients", bg: "linear-gradient(160deg,#064e3b 0%,#022c22 100%)", hl: "#6ee7b7", hook: "What's *actually* inside", items: ["Magnesium glycinate", "Magnesium malate", "Magnesium taurate", "Zero fillers"], tag: "Magnesium" },
    why: [
      "Naming each component turns a vague claim into something checkable.",
      "Numbered callouts guide the eye around the product in order.",
      "Four short labels are enough. More reads like a label, not an ad.",
    ],
    headline: "What's actually inside",
    primary: "Three forms of magnesium, no fillers. Every component listed, so you can check it yourself.",
  },
  {
    id: "stoplight-matrix", type: "static", trending: false,
    category: "Electronics", label: "Electronics", title: "Stop-Light Rating Matrix",
    format: "4:5 · Static · Comparison matrix", framework: "Comparison",
    art: { kind: "stoplight", bg: "linear-gradient(160deg,#1e293b 0%,#020617 100%)", hl: "#86efac", hook: "We tested *every* alternative", cols: ["You", "Typical", "Budget"], rows: [["Battery life", "g", "y", "r"], ["Water rating", "g", "y", "r"], ["Price", "g", "r", "g"]], tag: "Smartwatch" },
    why: [
      "Green, yellow and red are read instantly, before any text.",
      "A side-by-side matrix answers the shopper's next question for them.",
      "Rate competitors only where you have real test results.",
    ],
    headline: "We tested every alternative",
    primary: "Battery, water rating and price, side by side against the usual options. See where each one lands.",
  },
  {
    id: "customer-dm", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Customer DM Screenshot",
    format: "4:5 · Static · Message thread screenshot", framework: "Curiosity",
    art: { kind: "dm", bg: "linear-gradient(165deg,#4c1d95 0%,#0f172a 100%)", hl: "#f9a8d4", hook: "They *always* ask where it's from", recv: "Wait, where did you get that??", sent: "The new wool coat. It's Nordvik.", tag: "Outerwear" },
    why: [
      "A text thread looks private, so it reads as honest word of mouth.",
      "The question 'where did you get that?' is the exact moment you want to own.",
      "Keep the reply to one line so the product name lands.",
    ],
    headline: "They always ask where it's from",
    primary: "Every time I wear it someone asks. Here is where it comes from and why it is worth it.",
  },
  {
    id: "press-quote", type: "static", trending: false,
    category: "Local Services", label: "Local Services", title: "Press Quote Bar",
    format: "4:5 · Static · Authority banner", framework: "Authority",
    art: { kind: "press", bg: "linear-gradient(160deg,#334155 0%,#0f172a 100%)", hl: "#fde68a", hook: "*Press* loves it", quote: "The most reliable emergency dentist in the city.", pub: "City Weekly", tag: "Dental" },
    why: [
      "A third-party quote carries authority your own copy cannot.",
      "Pinned above the product, it is read first, like a masthead.",
      "Quote only coverage you actually received, word for word.",
    ],
    headline: "Press loves it",
    primary: "Independent coverage says it better than we can. Read the quote, then book your visit.",
  },
  {
    id: "before-after-split", type: "static", trending: true,
    category: "Local Services", label: "Local Services", title: "Before / After Split Screen",
    format: "4:5 · Static · Vertical split with metrics", framework: "Transformation",
    art: { kind: "beforeafter", bg: "linear-gradient(160deg,#0f172a 0%,#1e3a8a 100%)", hl: "#7dd3fc", hook: "Same smile. *One visit.*", before: { label: "Before", metric: "Shade A4" }, after: { label: "After", metric: "Shade A1" }, tag: "Dental" },
    why: [
      "A vertical split makes the change visible in one glance.",
      "Before and after badges remove any doubt about which side is which.",
      "One measurable number per side is more credible than adjectives.",
    ],
    headline: "Same smile. One visit.",
    primary: "One appointment, a measurable change. Book online and see the difference for yourself.",
  },
  {
    id: "trend-chart", type: "static", trending: false,
    category: "Supplements", label: "Supplements", title: "Chart / Graph Proof",
    format: "4:5 · Static · Trend line proof", framework: "Outcome",
    art: { kind: "chart", bg: "linear-gradient(165deg,#0c4a6e 0%,#020617 100%)", hl: "#7dd3fc", hook: "*30 days* of sleep data", start: ["Day 1", "58"], end: ["Day 30", "81"], metric: "sleep score", tag: "Sleep" },
    why: [
      "A rising line is understood faster than any sentence.",
      "Two labeled endpoints make the claim specific and easy to check.",
      "Use your own measured numbers. The curve only connects them.",
    ],
    headline: "30 days of sleep data",
    primary: "Tracked nightly for 30 days. Here is the trend, start to finish.",
  },
  {
    id: "review-static", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Beverage", title: "Review Headline Static",
    format: "4:5 · Static · Review as the headline", framework: "Social proof",
    art: { kind: "review", bg: "linear-gradient(160deg,#7c2d12 0%,#1c1917 100%)", hl: "#fdba74", hook: "Say it like a *customer* would", quote: "Zero prep time. Hunger fully satisfied.", who: "Verified buyer", initial: "J", tag: "Snacks" },
    why: [
      "The headline is a real customer sentence, so it reads as proof first and as an ad second.",
      "Five stars above the quote answer 'is it any good?' before the viewer asks.",
      "Short, plain words are easy to read at a glance and easy to test as variants.",
    ],
    headline: "Zero prep time. Hunger fully satisfied.",
    primary: "Real words from a real customer. Grab a box and see why they keep coming back.",
  },
  {
    id: "editorial-headline", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Editorial Breaking News",
    format: "4:5 · Static · Newspaper front page", framework: "Authority and curiosity",
    art: { kind: "newspaper", bg: "linear-gradient(160deg,#1e293b 0%,#020617 100%)", hl: "#fde68a", hook: "Make *the news* before they do", pub: "The Daily Fit", quote: "BREAKING: THE LINEN SHIRT IS TAKING OVER!", sub: "Why everyone is asking where it is from", tag: "Menswear" },
    why: [
      "A newspaper front page borrows the authority of news, so the claim feels reported instead of sold.",
      "'Breaking' and 'taking over' create urgency and curiosity in a single line.",
      "Keep it playful and true to your product. A fake claim here breaks trust fast.",
    ],
    headline: "The linen shirt is taking over",
    primary: "Everyone is talking about it. See what the fuss is about before your size is gone.",
  },
  {
    id: "text-message-static", type: "static", trending: false,
    category: "Local Services", label: "Home & Wellness", title: "Text Message Screenshot",
    format: "4:5 · Static · Friend-to-friend chat", framework: "Word of mouth",
    art: { kind: "dm", bg: "linear-gradient(165deg,#0c4a6e 0%,#0f172a 100%)", hl: "#7dd3fc", hook: "A *friend* told me about this", recv: "I'm so burnt out. Please send help.", sent: "Try the weighted blanket. My sleep changed in a week.", tag: "Sleep" },
    why: [
      "A chat between friends looks private, which makes the recommendation feel honest.",
      "The problem comes from the friend, and the product is the answer, so the pitch never feels pushed.",
      "Keep the reply to one sentence so the product name is the last thing read.",
    ],
    headline: "A friend told me about this",
    primary: "It started as a text. Now it is the first thing I recommend to anyone who is tired.",
  },
  {
    id: "old-me-new-me", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Beverage", title: "Old Me vs New Me",
    format: "4:5 · Static · Problem and solution split", framework: "Transformation",
    art: { kind: "beforeafter", bg: "linear-gradient(160deg,#78350f 0%,#1c1917 100%)", hl: "#fcd34d", hook: "Old me. *New me.*", before: { label: "Old me", metric: "No time to cook" }, after: { label: "New me", metric: "Dinner in 20 min" }, tag: "Meal kits" },
    why: [
      "Two sides make the change obvious in one second, with no explanation needed.",
      "'Old me' is the viewer's current pain, and 'New me' is the result they want.",
      "Use one clear problem and one clear fix. Two pains on one side blur the message.",
    ],
    headline: "Old me. New me.",
    primary: "From no time to cook to dinner in 20 minutes. Here is how the switch happened.",
  },
  {
    id: "comment-thread-ad", type: "static", trending: true,
    category: "Supplements", label: "Supplements", title: "Comment Section Ad",
    format: "4:5 · Static · Forum question and reply", framework: "Native social proof",
    art: { kind: "tweet", bg: "linear-gradient(160deg,#14532d 0%,#052e16 100%)", hl: "#86efac", hook: "Someone *asked* the question", text: "Any protein shake that isn't chalky? Reply: Tastes like dessert, keeps me full till lunch.", name: "r/fitfood", handle: "u/meal_prep_mia · 5d", tag: "Protein" },
    why: [
      "A real question and a real answer is the exact moment a buyer is deciding.",
      "The familiar forum card feels like content, so the ad is not scrolled past as an ad.",
      "Only use replies you have permission to share, or write a clearly typical one.",
    ],
    headline: "Someone asked the question",
    primary: "Same question we get every week. Here is the answer people keep giving.",
  },
  {
    id: "door-hanger", type: "static", trending: true,
    category: "Travel", label: "Travel", title: "Door Hanger Sign",
    format: "4:5 · Static · Hotel door hanger", framework: "Humour",
    art: { kind: "offer", bg: "linear-gradient(160deg,#0c4a6e 0%,#0f172a 100%)", hl: "#7dd3fc", hook: "Do not disturb: *island time*", big: "€429", sub: "4 nights in Santorini", pills: ["Sea view", "Breakfast"], cta: "Book now", tag: "Island stay" },
    why: [
      "A door hanger is a familiar object, so the viewer reads the message in a second.",
      "A joke on the sign makes the offer feel human, not like an ad.",
      "The price and the destination sit on the sign itself, so nothing else is needed.",
    ],
    headline: "Do not disturb: island time",
    primary: "4 nights in Santorini with sea view and breakfast. From €429.",
  },
  {
    id: "habit-wall", type: "static", trending: true,
    category: "Supplements", label: "Supplements", title: "Habit Streak Calendar",
    format: "4:5 · Static · 30 days, 28 done", framework: "Consistency",
    art: { kind: "timeline", bg: "linear-gradient(160deg,#14532d 0%,#0f172a 100%)", hl: "#86efac", hook: "*30 days.* 28 done.", points: [["Day 1", "ok", "Started"], ["Day 28", "ok", "Still going"]], foot: "A routine you can actually keep", tag: "Daily greens" },
    why: [
      "A wall of ticked boxes shows consistency at a glance and makes quitting feel like a loss.",
      "28 of 30 is believable. A perfect score would look fake.",
      "The product stands beside the calendar, so the habit and the product are linked.",
    ],
    headline: "30 days. 28 done.",
    primary: "One scoop a day, easy enough to keep. Start your 30-day streak.",
  },
  {
    id: "luggage-tag", type: "static", trending: true,
    category: "Travel", label: "Travel", title: "Luggage Tag Offer",
    format: "4:5 · Static · Tag on a suitcase", framework: "Specificity",
    art: { kind: "offer", bg: "linear-gradient(160deg,#78350f 0%,#0f172a 100%)", hl: "#fcd34d", hook: "Destination: *Naxos*", big: "€379", sub: "5 nights, flights included", pills: ["Carry-on included"], cta: "See dates", tag: "Island trip" },
    why: [
      "A luggage tag turns the offer into a real departure, so the viewer pictures leaving.",
      "Destination, nights and price fit on one tag, which keeps the message tight.",
      "The sunny airport background tells the story before any text is read.",
    ],
    headline: "Destination: Naxos",
    primary: "5 nights with flights included. From €379.",
  },
  {
    id: "lock-screen", type: "static", trending: true,
    category: "Supplements", label: "Supplements", title: "Lock Screen Alert",
    format: "4:5 · Static · Phone notification", framework: "Pattern interrupt",
    art: { kind: "dm", bg: "linear-gradient(160deg,#4c1d95 0%,#0f172a 100%)", hl: "#c4b5fd", hook: "Notification *cancelled*", tag: "Energy" },
    why: [
      "A phone notification is the most familiar format on the screen, so it stops the scroll.",
      "The alert names a specific moment (the 3 pm slump), which makes the benefit concrete.",
      "The product sits next to the phone so the viewer connects the fix to the thing.",
    ],
    headline: "Your 3 PM slump was cancelled",
    primary: "Steady energy through the afternoon. Try the first tub risk free.",
  },
  {
    id: "suitcase-stickers", type: "static", trending: true,
    category: "Travel", label: "Travel", title: "Suitcase Sticker Wall",
    format: "4:5 · Static · Next destination", framework: "Collection",
    art: { kind: "checklist", bg: "linear-gradient(160deg,#7c2d12 0%,#1c1917 100%)", hl: "#fdba74", hook: "Next sticker: *Lisbon*", items: ["Flights", "3 nights", "Breakfast"], chip: "From €349", tag: "City break" },
    why: [
      "Stickers on a worn case say 'travel' without a word, so the offer feels like part of a story.",
      "One empty space and one new sticker makes the next trip feel natural.",
      "Every detail on the sticker is a fact, not an adjective.",
    ],
    headline: "Next sticker: Lisbon",
    primary: "3 nights in Lisbon with flights and breakfast. From €349.",
  },
  {
    id: "pharmacy-label", type: "static", trending: true,
    category: "Supplements", label: "Supplements", title: "Pharmacy Label Joke",
    format: "4:5 · Static · Prescription-style label", framework: "Humour",
    art: { kind: "quote", bg: "linear-gradient(160deg,#075985 0%,#0f172a 100%)", hl: "#7dd3fc", hook: "Take *one* daily", text: "Side effects: better mornings, steady focus, fewer coffees.", sign: "Daily capsule", tag: "Multivitamin" },
    why: [
      "A pharmacy label is instantly recognised and lets you joke while sounding clear.",
      "'Side effects: better mornings' flips the usual warning into a benefit.",
      "Keep the claims light and true. Do not copy real medicine language.",
    ],
    headline: "Take one daily",
    primary: "Side effects: better mornings. Start your first bottle today.",
  },
  {
    id: "snow-globe", type: "static", trending: true,
    category: "Travel", label: "Travel", title: "Snow Globe Escape",
    format: "4:5 · Static · A beach in a globe", framework: "Contrast",
    art: { kind: "split", bg: "linear-gradient(160deg,#1e3a8a 0%,#0f172a 100%)", hl: "#93c5fd", hook: "A *beach* on your desk", left: { label: "Your desk", metric: "Rain", note: "Monday" }, right: { label: "Inside", metric: "Sun", note: "from €299" }, tag: "Escape" },
    why: [
      "A tiny beach inside a snow globe shows the escape fantasy in a single object.",
      "The grey office around it makes the colour of the globe pop.",
      "Price on the base of the globe keeps it part of the image.",
    ],
    headline: "A beach on your desk",
    primary: "Swap the grey week for 4 sunny nights. From €299.",
  },
  {
    id: "pantry-swap", type: "static", trending: true,
    category: "Supplements", label: "Supplements", title: "Pantry Shelf Swap",
    format: "4:5 · Static · Six bottles to one", framework: "Simplicity",
    art: { kind: "split", bg: "linear-gradient(160deg,#3f3f46 0%,#18181b 100%)", hl: "#bef264", hook: "*6 bottles* to *1 scoop*", left: { label: "Before", metric: "6", note: "bottles" }, right: { label: "Now", metric: "1", note: "scoop" }, tag: "All-in-one" },
    why: [
      "Replacing a crowded shelf with one product is a clear and visible saving.",
      "Numbers (6 to 1) make the claim concrete and easy to check.",
      "Be accurate. Only claim it replaces products it really does.",
    ],
    headline: "6 bottles to 1 scoop",
    primary: "One scoop replaces your whole shelf. Try it for 30 days.",
  },
  {
    id: "sand-message", type: "static", trending: true,
    category: "Travel", label: "Travel", title: "Message In The Sand",
    format: "4:5 · Static · Words on a beach", framework: "Humour",
    art: { kind: "neon", bg: "linear-gradient(160deg,#0c4a6e 0%,#164e63 100%)", hl: "#fde68a", hook: "Out of *office*", label: "5 nights · from €379", tag: "Beach break" },
    why: [
      "Words written in sand look hand-made, so the ad feels personal.",
      "The sea in the background carries the emotion, the sand carries the offer.",
      "A short line like this is easy to read even as a small thumbnail.",
    ],
    headline: "Out of office",
    primary: "5 nights by the sea from €379. Your calendar can wait.",
  },
  {
    id: "sunrise-sill", type: "static", trending: true,
    category: "Supplements", label: "Supplements", title: "Sunrise Windowsill",
    format: "4:5 · Static · Morning note", framework: "Routine",
    art: { kind: "quote", bg: "linear-gradient(160deg,#9a3412 0%,#1c1917 100%)", hl: "#fdba74", hook: "*Day 1* of no third coffee", text: "Day 1 of not needing a third coffee.", sign: "A note on the windowsill", tag: "Morning mix" },
    why: [
      "A sticky note on a windowsill feels like a real person's diary, which builds trust.",
      "Golden sunrise light makes the product look like part of a good morning.",
      "A single small, believable promise beats a big claim.",
    ],
    headline: "Day 1 of no third coffee",
    primary: "A morning mix made to replace your third cup.",
  },
  {
    id: "mirror-notes", type: "static", trending: true,
    category: "Beauty & Skincare", label: "Beauty & Skincare", title: "Mirror Sticky Notes",
    format: "4:5 · Static · Routine on the mirror", framework: "Simplicity",
    art: { kind: "checklist", bg: "linear-gradient(160deg,#831843 0%,#0f172a 100%)", hl: "#f9a8d4", hook: "Three steps. *Done.*", items: ["AM: cleanse", "AM: serum", "PM: that is it"], chip: "A routine you keep", tag: "Skincare" },
    why: [
      "Sticky notes on a mirror are how real routines look, so the ad feels personal.",
      "Three short notes make the routine look easy to follow.",
      "The product sits below the notes so the fix and the steps are linked.",
    ],
    headline: "Three steps. Done.",
    primary: "A skincare routine short enough to keep. Start with the first bottle today.",
  },
  {
    id: "photo-booth", type: "static", trending: true,
    category: "Beauty & Skincare", label: "Beauty & Skincare", title: "Photo Booth Strip",
    format: "4:5 · Static · Four frames, four weeks", framework: "Proof over time",
    art: { kind: "timeline", bg: "linear-gradient(160deg,#4c1d95 0%,#0f172a 100%)", hl: "#c4b5fd", hook: "*4 weeks*, 4 frames", points: [["Week 1", "bad", "Dull"], ["Week 4", "ok", "Glowing"]], foot: "Same face, same light", tag: "Skincare" },
    why: [
      "A photo-booth strip is a familiar object that shows change in four frames.",
      "Week labels make the timeline believable and easy to check.",
      "Keep the lighting identical in every frame so the proof stays honest.",
    ],
    headline: "4 weeks, 4 frames",
    primary: "Same face, same light, four weeks apart. See the change for yourself.",
  },
  {
    id: "label-magnifier", type: "static", trending: true,
    category: "Beauty & Skincare", label: "Beauty & Skincare", title: "Label Magnifier",
    format: "4:5 · Static · Ingredients under glass", framework: "Transparency",
    art: { kind: "stat", bg: "linear-gradient(160deg,#14532d 0%,#0f172a 100%)", hl: "#86efac", hook: "*Read* the label", big: "5", unit: "ingredients on the label", chips: ["Nothing hidden", "Full list shown"], tag: "Clean skincare" },
    why: [
      "A magnifying glass over the label says 'we have nothing to hide'.",
      "One number (5 ingredients) is easy to remember and easy to compare.",
      "List only what is really in the product so the claim holds up.",
    ],
    headline: "Read the label",
    primary: "Five ingredients, all listed in full. See exactly what goes on your skin.",
  },
  {
    id: "carry-on-kit", type: "static", trending: true,
    category: "Beauty & Skincare", label: "Beauty & Skincare", title: "Carry-On Kit",
    format: "4:5 · Static · Travel-size routine", framework: "Convenience",
    art: { kind: "offer", bg: "linear-gradient(160deg,#0c4a6e 0%,#0f172a 100%)", hl: "#7dd3fc", hook: "Airport *approved*", big: "100ml", unit: "", sub: "carry-on size", pills: ["Leak-proof", "Full routine"], cta: "Get the kit", tag: "Travel kit" },
    why: [
      "A clear travel bag is a familiar object that shows the size at a glance.",
      "'Airport approved' answers the one question every traveller has.",
      "Show the real kit so the size matches what arrives.",
    ],
    headline: "Airport approved",
    primary: "Your full routine in carry-on sizes. One clear bag, nothing to decant.",
  },
  {
    id: "swing-tag", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Swing Tag Price",
    format: "4:5 · Static · Tag on the garment", framework: "Clarity",
    art: { kind: "offer", bg: "linear-gradient(160deg,#78350f 0%,#1c1917 100%)", hl: "#fcd34d", hook: "The *linen shirt*", big: "€39", sub: "free returns · 60 days", pills: ["Pre-washed", "Sizes XS to XXL"], cta: "Shop the shirt", tag: "Menswear" },
    why: [
      "A swing tag is the real place a price lives, so it reads as honest.",
      "Printing the return window on the tag removes the biggest buying fear.",
      "The garment fills the frame so the fabric does the selling.",
    ],
    headline: "The linen shirt, €39",
    primary: "Free returns for 60 days. Pre-washed, soft from the first wear.",
  },
  {
    id: "fitting-room", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Fitting Room Sign",
    format: "4:5 · Static · Curtain and hanger", framework: "Social proof",
    art: { kind: "review", bg: "linear-gradient(160deg,#581c87 0%,#0f172a 100%)", hl: "#e9d5ff", hook: "Fits like it was *made for you*", quote: "I bought my usual size and it fit first time.", who: "Verified buyer", initial: "M", tag: "Denim" },
    why: [
      "A fitting-room scene answers 'will it fit?' before the viewer asks.",
      "A real review on the hanger tag reads as proof, not as a slogan.",
      "Mention the exact size experience so the claim is specific.",
    ],
    headline: "Fits like it was made for you",
    primary: "True to size, so you can order your usual. Free returns if it is not right.",
  },
  {
    id: "empty-closet", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "One Tee Closet",
    format: "4:5 · Static · Empty wardrobe", framework: "Simplicity",
    art: { kind: "stat", bg: "linear-gradient(160deg,#3f3f46 0%,#18181b 100%)", hl: "#bef264", hook: "One tee. *30 ways.*", big: "30", unit: "outfits from one tee", chips: ["Heavyweight cotton", "Holds its shape"], tag: "Basics" },
    why: [
      "An almost empty wardrobe with one tee says 'this is all you need'.",
      "A number (30 ways) turns a basic into a system.",
      "Show the tee styled differently so the number feels believable.",
    ],
    headline: "One tee. 30 ways.",
    primary: "One heavyweight tee that goes with everything. Free returns.",
  },
  {
    id: "sunday-drop", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Sunday Drop Bulletin",
    format: "4:5 · Static · Church bulletin card", framework: "Scarcity",
    art: { kind: "restock", bg: "linear-gradient(160deg,#1e3a8a 0%,#0f172a 100%)", hl: "#93c5fd", hook: "New *Sunday* drop", big: "SUN", sub: "limited run", pills: ["Heavyweight", "Faith apparel"], cta: "Shop the drop", tag: "Faith apparel" },
    why: [
      "A printed bulletin card is a familiar object for the exact audience, so it feels like theirs.",
      "'Sunday drop' sets a schedule people can plan around.",
      "A limited run adds a real reason to act now. Only use it if it is true.",
    ],
    headline: "New Sunday drop",
    primary: "A limited run of heavyweight faith apparel. When it is gone, it is gone.",
  },
  {
    id: "battery-note", type: "static", trending: true,
    category: "Electronics", label: "Electronics", title: "Battery Sticky Note",
    format: "4:5 · Static · Charged once", framework: "Specificity",
    art: { kind: "stat", bg: "linear-gradient(160deg,#1e1b4b 0%,#0f172a 100%)", hl: "#a5b4fc", hook: "Charged *once*", big: "7", unit: "days on one charge", chips: ["Fast charge", "USB-C"], tag: "Earbuds" },
    why: [
      "A sticky note on the charging case feels like a real owner's note.",
      "'7 days' is a number a buyer can picture in their week.",
      "State how the battery was measured so the claim stays honest.",
    ],
    headline: "Charged once. Used all week.",
    primary: "Seven days of listening on one charge. Back to 100% in under an hour.",
  },
  {
    id: "tangle-free", type: "static", trending: true,
    category: "Electronics", label: "Electronics", title: "Cable Knot Reveal",
    format: "4:5 · Static · Tangled versus tidy", framework: "Contrast",
    art: { kind: "split", bg: "linear-gradient(160deg,#164e63 0%,#0f172a 100%)", hl: "#67e8f9", hook: "*Tangle-free*", left: { label: "Before", metric: "Knots", note: "every morning" }, right: { label: "Now", metric: "0", note: "tangles" }, tag: "Cables" },
    why: [
      "A knot of cable against a neat coil shows the benefit in one look.",
      "Everyone has lived the problem, so it needs no explaining.",
      "Keep the 'after' side real: show the actual cable.",
    ],
    headline: "Tangle-free",
    primary: "A flat braided cable that does not knot. Free returns for 60 days.",
  },
  {
    id: "one-pad", type: "static", trending: true,
    category: "Electronics", label: "Electronics", title: "One Pad Desk",
    format: "4:5 · Static · Clean desk", framework: "Simplicity",
    art: { kind: "split", bg: "linear-gradient(160deg,#27272a 0%,#09090b 100%)", hl: "#e4e4e7", hook: "One pad. *Zero cables.*", left: { label: "Before", metric: "4", note: "chargers" }, right: { label: "Now", metric: "1", note: "pad" }, tag: "Wireless charger" },
    why: [
      "A tidy desk is a feeling most buyers want, so the image sells before the text.",
      "'4 to 1' is a clear, easy to remember saving.",
      "Show the real pad and the real devices it charges.",
    ],
    headline: "One pad. Zero cables.",
    primary: "Charge your phone, watch and earbuds on one pad. Free shipping.",
  },
  {
    id: "fridge-booking", type: "static", trending: true,
    category: "Local Services", label: "Local Services", title: "Fridge Magnet Booking",
    format: "4:5 · Static · Appointment on the fridge", framework: "Ease",
    art: { kind: "checklist", bg: "linear-gradient(160deg,#075985 0%,#0f172a 100%)", hl: "#7dd3fc", hook: "Booked in *60 seconds*", items: ["Pick your day", "Fixed price shown", "We bring everything"], chip: "From €49", tag: "Home cleaning" },
    why: [
      "An appointment card on a fridge is how bookings really live at home.",
      "'60 seconds' and 'fixed price' remove the two biggest worries.",
      "Show the real price so the booking feels safe.",
    ],
    headline: "Booked in 60 seconds",
    primary: "Pick a day, see the fixed price, we bring everything. From €49.",
  },
  {
    id: "van-clipboard", type: "static", trending: true,
    category: "Local Services", label: "Local Services", title: "Van Door Clipboard",
    format: "4:5 · Static · Tradesman's van", framework: "Trust",
    art: { kind: "checklist", bg: "linear-gradient(160deg,#14532d 0%,#0f172a 100%)", hl: "#86efac", hook: "On time, *fixed price*", items: ["Arrival window: 08:00 to 10:00", "Fixed price quote", "Work guaranteed"], chip: "Licensed and insured", tag: "Plumbing" },
    why: [
      "A tidy van and a clipboard signal a professional before anyone speaks.",
      "An arrival window and fixed price answer the two main fears about trades.",
      "Only promise what the business really delivers.",
    ],
    headline: "On time, fixed price",
    primary: "Arrival window, fixed price and a guarantee on the work. Book online.",
  },
  {
    id: "barber-receipt", type: "static", trending: true,
    category: "Local Services", label: "Local Services", title: "Barber Chair Receipt",
    format: "4:5 · Static · Price on the receipt", framework: "Price clarity",
    art: { kind: "offer", bg: "linear-gradient(160deg,#7c2d12 0%,#1c1917 100%)", hl: "#fdba74", hook: "Fresh cut. *Fixed price.*", big: "€18", sub: "cut and beard", pills: ["No booking fee", "Walk-ins welcome"], cta: "Book a chair", tag: "Barber" },
    why: [
      "A receipt on the barber chair makes the price part of the scene.",
      "'Fixed price' and 'no booking fee' remove hidden-cost worries.",
      "The real shop gives the ad local trust no stock photo can.",
    ],
    headline: "Fresh cut. Fixed price.",
    primary: "Cut and beard for €18. Walk-ins welcome, online booking free.",
  },
  {
    id: "lunch-break", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Bev", title: "Lunch Break Note",
    format: "4:5 · Static · Desk lunch", framework: "Convenience",
    art: { kind: "review", bg: "linear-gradient(160deg,#365314 0%,#1c1917 100%)", hl: "#bef264", hook: "Lunch, *sorted*", quote: "Ready in 3 minutes and actually filling.", who: "Verified buyer", initial: "A", tag: "Meals" },
    why: [
      "A lunch on a desk is the exact moment the product is used.",
      "A short customer line reads as proof, not as a slogan.",
      "Give the real time to prepare so the promise is checkable.",
    ],
    headline: "Lunch, sorted",
    primary: "A proper meal in 3 minutes. Fresh ingredients, no prep.",
  },
  {
    id: "cup-sleeve", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Bev", title: "Cup Sleeve Message",
    format: "4:5 · Static · Message on the sleeve", framework: "Pattern interrupt",
    art: { kind: "neon", bg: "linear-gradient(160deg,#451a03 0%,#1c1917 100%)", hl: "#fbbf24", hook: "*Not* your usual", label: "Single origin, fresh roasted", tag: "Coffee" },
    why: [
      "A message printed on the cup sleeve is read in the exact moment of use.",
      "'Not your usual' sparks curiosity and invites a try.",
      "Name something real (origin, roast date) so the claim is backed up.",
    ],
    headline: "Not your usual",
    primary: "Single origin, roasted this week. Your first bag ships free.",
  },
  {
    id: "pizza-lid", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Bev", title: "Pizza Box Review",
    format: "4:5 · Static · Review on the box", framework: "Social proof",
    art: { kind: "review", bg: "linear-gradient(160deg,#7f1d1d 0%,#1c1917 100%)", hl: "#fca5a5", hook: "Written on the *box*", quote: "10 out of 10. Would order again tonight.", who: "A hungry customer", initial: "D", tag: "Pizza" },
    why: [
      "A pen review on the box lid feels spontaneous and real.",
      "The scoring is simple and instantly understood.",
      "Use real quotes from your customers.",
    ],
    headline: "Written on the box",
    primary: "Stone-baked and delivered hot. Order before 9 pm.",
  },
  {
    id: "alarm-tub", type: "static", trending: true,
    category: "Supplements", label: "Supplements", title: "Alarm Clock Snooze",
    format: "4:5 · Static · 06:30", framework: "Routine",
    art: { kind: "stat", bg: "linear-gradient(160deg,#1e293b 0%,#020617 100%)", hl: "#7dd3fc", hook: "*Snooze* less", big: "6:30", unit: "wake up on the first alarm", chips: ["Natural caffeine", "No crash"], tag: "Morning mix" },
    why: [
      "An alarm clock and a tub tell a morning story in one frame.",
      "The time (6:30) makes the moment specific.",
      "Keep the promise modest: help with mornings, not miracles.",
    ],
    headline: "Snooze less",
    primary: "A morning mix for the first alarm. Try it for 30 days.",
  },
  {
    id: "foggy-window", type: "static", trending: true,
    category: "Travel", label: "Travel", title: "Foggy Window Note",
    format: "4:5 · Static · Finger-written message", framework: "Curiosity",
    art: { kind: "neon", bg: "linear-gradient(160deg,#334155 0%,#0f172a 100%)", hl: "#fde68a", hook: "Next stop: *Crete*", label: "4 nights · from €329", tag: "Island break" },
    why: [
      "Words drawn on a foggy window look personal and hand-made.",
      "The view through the letters shows the destination without a stock photo.",
      "Keep the offer short: place, nights, price.",
    ],
    headline: "Next stop: Crete",
    primary: "4 nights in Crete from €329. Flights included.",
  },
  {
    id: "beach-bag", type: "static", trending: true,
    category: "Travel", label: "Travel", title: "Beach Bag Packed",
    format: "4:5 · Static · Open bag", framework: "Ease",
    art: { kind: "checklist", bg: "linear-gradient(160deg,#0e7490 0%,#0f172a 100%)", hl: "#a5f3fc", hook: "Packed in *5 minutes*", items: ["Towel", "Sunscreen", "Check-in 14:00"], chip: "From €269", tag: "Beach break" },
    why: [
      "An open beach bag shows the trip as already happening.",
      "The check-in time makes the plan feel real and close.",
      "The sea behind the bag carries the feeling, the card carries the price.",
    ],
    headline: "Packed in 5 minutes",
    primary: "3 nights by the sea, check-in at 14:00. From €269.",
  },
  {
    id: "plain-hoodie", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Heavyweight Hoodie Rail",
    format: "4:5 · Static · Plain hoodie on a boutique rail", framework: "Clarity",
    art: { kind: "offer", bg: "linear-gradient(160deg,#450a0a 0%,#0c0a09 100%)", hl: "#fca5a5", hook: "Wear what you *believe*", big: "€58", sub: "heavyweight · built to last", pills: ["Heavyweight", "Unisex fit"], cta: "Shop hoodies", tag: "Faith apparel" },
    why: [
      "A plain black hoodie on a rail lets the fabric and fit do the selling, with the drawstrings showing the details.",
      "A whitewashed boutique wall keeps the focus on the product and feels premium.",
      "The price sits next to the promise, so there is nothing to hunt for.",
    ],
    headline: "Wear what you believe.",
    primary: "Heavyweight black hoodies with a premium feel. From €49.",
  },
  {
    id: "athos-peg", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Holy Mountain Peg",
    format: "4:5 · Static · Hoodie on a monastery peg", framework: "Story",
    art: { kind: "offer", bg: "linear-gradient(160deg,#292524 0%,#0c0a09 100%)", hl: "#fcd34d", hook: "Inspired by *Mount Athos*", big: "€49", unit: "from", sub: "faith, worn daily", pills: ["Black heavyweight", "Faith inspired"], cta: "Shop the collection", tag: "Faith apparel" },
    why: [
      "A hoodie on a wooden peg in a stone corridor is a story told with one object.",
      "'Inspired by Mount Athos' says where the designs come from, which is what this audience cares about.",
      "The 'from' price lowers the first click without hiding the range.",
    ],
    headline: "Inspired by Mount Athos",
    primary: "Hoodies and tees drawn from the lives of the saints and the monks of the Holy Mountain. From €49.",
  },
  {
    id: "quiet-hour", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Candle & Prayer Rope",
    format: "4:5 · Static · Folded hoodie, free shipping card", framework: "Clarity",
    art: { kind: "stat", bg: "linear-gradient(160deg,#422006 0%,#0c0a09 100%)", hl: "#fbbf24", hook: "Free shipping over *€90*", big: "€90", unit: "worldwide, no code", chips: ["Ships in 1-3 days", "EU & USA"], tag: "Faith apparel" },
    why: [
      "A candle and a prayer rope tell the right buyer this is for them before a word is read.",
      "The shipping threshold is the biggest number, because it is what changes the basket.",
      "Real delivery times beat vague promises.",
    ],
    headline: "Free shipping over €90",
    primary: "Worldwide free shipping on orders over €90. Ships in 1-3 business days from the USA and Europe.",
  },
  {
    id: "replacement-promise", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Free Replacement Card",
    format: "4:5 · Static · Unboxing guarantee", framework: "Risk reversal",
    art: { kind: "checklist", bg: "linear-gradient(160deg,#1c1917 0%,#0c0a09 100%)", hook: "*Defect?* Free replacement", items: ["Damaged in the post", "Misprinted", "Faulty stitching"], chip: "No restocking fees", tag: "Faith apparel" },
    why: [
      "A card inside the box is the exact moment a buyer wonders if anything could go wrong.",
      "Naming the three problems makes the promise specific and believable.",
      "Only promise what your policy really covers: this is for defects, not size changes.",
    ],
    headline: "Defect? Free replacement.",
    primary: "If anything arrives damaged, misprinted or defective, we replace it for free. No restocking fees.",
  },
  {
    id: "street-poster", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Wheatpaste Street Poster",
    format: "4:5 · Static · Street poster, hoodie from behind", framework: "Pattern interrupt",
    art: { kind: "quote", bg: "linear-gradient(160deg,#7f1d1d 0%,#0c0a09 100%)", hl: "#fecaca", hook: "Not just for *Sunday*", text: "Wear it outside church too.", sign: "Faith apparel", tag: "Faith apparel" },
    why: [
      "A street poster stops a scroll the way a real one stops a walker.",
      "It speaks to men who want their faith to show up in the week, not only on Sunday.",
      "One short line is enough. The black hoodie does the rest.",
    ],
    headline: "Wear it outside church too.",
    primary: "Faith apparel for the other six days. Heavyweight hoodies and tees, from €49.",
  },
  {
    id: "gift-tag", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Gift Tag For Them",
    format: "4:5 · Static · Wrapped hoodie with a tag", framework: "Emotion",
    art: { kind: "offer", bg: "linear-gradient(160deg,#431407 0%,#0c0a09 100%)", hl: "#fdba74", hook: "For the one who *prays for you*", big: "€58", sub: "a gift that means something", pills: ["Heavyweight", "Ships in 1-3 days"], cta: "Send the gift", tag: "Gifts" },
    why: [
      "A handwritten-feel gift tag turns a hoodie into a message for someone specific.",
      "The line speaks to the gift giver, who is often a different person from the wearer.",
      "Shipping time matters most for gifts, so it sits in the pills.",
    ],
    headline: "For the one who prays for you",
    primary: "A heavyweight black hoodie, folded and ready to give. €58, ships in 1-3 days.",
  },
  {
    id: "everyday-tee", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Everyday Black Tee",
    format: "4:5 · Static · Plain tee on a boutique rail", framework: "Clarity",
    art: { kind: "quote", bg: "linear-gradient(160deg,#1c1917 0%,#000000 100%)", hl: "#d6d3d1", hook: "The tee you *reach for*", text: "Heavyweight cotton. Made to be worn daily.", sign: "Faith apparel", tag: "Faith apparel" },
    why: [
      "A clean tee on a rail is easy to trust: you see exactly what you get.",
      "One line about the fabric answers the main question before it is asked.",
      "Hanging on a real rail makes the shot honest and easy to trust.",
    ],
    headline: "The tee you reach for",
    primary: "A heavyweight black tee made to be worn every day. From €49.",
  },
  {
    id: "bakery-window", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Beverages", title: "Bakery Window After Dark",
    format: "4:5 · Static · Night shop window", framework: "Anticipation",
    art: { kind: "quote", bg: "linear-gradient(160deg,#451a03 0%,#0c0a09 100%)", hl: "#fcd34d", hook: "Worth *waiting* for", text: "open at 6am", sign: "Fresh every morning", tag: "Bakery" },
    why: [
      "A lit window in a dark street is a scene people stop for, and it builds anticipation for the product.",
      "The opening time is the offer: it gives a clear time to come back.",
      "One short line of gold script keeps the photo in charge.",
    ],
    headline: "Open at 6am",
    primary: "Fresh bread and pastries, baked before the city wakes up. Come by from 6am.",
  },
  {
    id: "masthead-behind", type: "static", trending: true,
    category: "Supplements", label: "Supplements", title: "Masthead Behind The Bottle",
    format: "4:5 · Static · Giant word behind product", framework: "Clarity",
    art: { kind: "offer", bg: "linear-gradient(160deg,#334155 0%,#0f172a 100%)", hl: "#bfdbfe", hook: "Your *evening* ritual", big: "REST", sub: "sleep support · 60 capsules", pills: ["Small batch", "Evening ritual"], cta: "Shop now", tag: "Sleep support" },
    why: [
      "One giant word names the benefit before anyone reads the label.",
      "The bottle overlapping the letters ties the product to the promise.",
      "Soft window light and a calm palette match the feeling of the benefit.",
    ],
    headline: "Your evening ritual",
    primary: "A small-batch sleep support blend for your evening routine. Only claim what your label and local rules allow.",
  },
  {
    id: "dawn-voice-note", type: "static", trending: true,
    category: "Beauty & Skincare", label: "Beauty & Cosmetics", title: "Dawn Voice Note",
    format: "4:5 · Static · Hand-held product, voice message", framework: "Social proof",
    art: { kind: "quote", bg: "linear-gradient(160deg,#9f1239 0%,#1e1b4b 100%)", hl: "#fecdd3", hook: "Heard it from a *friend*", text: "wear it daily", sign: "voice note · 0:07", tag: "Sunscreen" },
    why: [
      "A voice-message bubble looks like a recommendation from a friend, not an ad.",
      "A hand holding the product against open sky feels real and keeps the product the hero.",
      "The line is a habit instruction, not a claim you have to prove.",
    ],
    headline: "Wear it daily",
    primary: "The sunscreen people recommend by voice note. Light texture, easy to wear every day.",
  },
  {
    id: "chrome-type-stage", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Beverages", title: "Chrome Type Stage",
    format: "4:5 · Static · Giant 3D type behind a can", framework: "Pattern interrupt",
    art: { kind: "offer", bg: "linear-gradient(160deg,#c2410c 0%,#431407 100%)", hl: "#fed7aa", hook: "Skip the *rest*", big: "ONE", unit: "can", sub: "the only one you need", pills: ["Zero sugar", "Cold-ready"], cta: "Grab a can", tag: "Energy drink" },
    why: [
      "Giant chrome letters are impossible to scroll past, and the can sits right in the message.",
      "Three short words say the whole positioning: pick this one.",
      "A plain peach backdrop keeps the shiny type and the can in focus.",
    ],
    headline: "Skip the rest",
    primary: "One can, one decision. Only state sugar or caffeine claims your label supports.",
  },
  {
    id: "yes-maybe-hoodie", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Yes Or Maybe Later",
    format: "4:5 · Static · Floating hoodie with choice buttons", framework: "Pattern interrupt",
    art: { kind: "offer", bg: "linear-gradient(160deg,#1e3a8a 0%,#0f172a 100%)", hl: "#93c5fd", hook: "Say *yes* to the hoodie", big: "€49", unit: "from", sub: "heavyweight · plain black", pills: ["Heavyweight", "Free shipping over €90"], cta: "Yes, please", tag: "Hoodies" },
    why: [
      "Two choice buttons turn an ad into a tiny decision, and almost everyone taps yes.",
      "A plain floating hoodie is the product shown cleanly, with nothing competing.",
      "The price sits where the eye lands after the buttons.",
    ],
    headline: "Say yes to the hoodie",
    primary: "A heavyweight black hoodie, from €49. Free shipping on orders over €90.",
  },
  {
    id: "toggle-card", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Beverages", title: "Settings Toggle Card",
    format: "4:5 · Static · Jar with a settings card", framework: "Clarity",
    art: { kind: "checklist", bg: "linear-gradient(160deg,#166534 0%,#14532d 100%)", hl: "#bbf7d0", hook: "Your *breakfast* settings", items: ["Crunchy", "Oat based", "Zero fuss"], chip: "Ready to eat", tag: "Granola" },
    why: [
      "A settings card turns three benefits into something people read like a menu.",
      "Toggles set to ON make every claim feel like a choice already made.",
      "The jar stays in the foreground, so the product is the first thing you see.",
    ],
    headline: "Your breakfast settings",
    primary: "Crunchy, oat-based granola with zero fuss. Only list traits that are true for your recipe.",
  },
  {
    id: "order-alert-stack", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Beverages", title: "Order Alert Stack",
    format: "4:5 · Static · Phone alerts over a coffee bag", framework: "Anticipation",
    art: { kind: "checklist", bg: "linear-gradient(160deg,#78350f 0%,#1c1917 100%)", hl: "#fde68a", hook: "Your coffee is *on its way*", items: ["Your order has shipped", "Fresh roasted Monday", "Arrives tomorrow"], chip: "Roasted to order", tag: "Coffee" },
    why: [
      "Notification banners are the most-read format on a phone, so people read them without thinking.",
      "The three alerts tell the whole delivery story in six seconds.",
      "Only claim a roast day and delivery date you can actually keep.",
    ],
    headline: "Your coffee is on its way",
    primary: "Roasted to order and shipped fast. Check the roast day and delivery promise before you run this.",
  },
  {
    id: "progress-ring", type: "static", trending: true,
    category: "Supplements", label: "Supplements", title: "Day 27 Progress Ring",
    format: "4:5 · Static · Glowing ring around a tub", framework: "Habit",
    art: { kind: "stat", bg: "linear-gradient(160deg,#14532d 0%,#020617 100%)", hl: "#86efac", hook: "Almost at *day 30*", big: "27/30", unit: "days", chips: ["30-day routine", "Small daily step"], tag: "Supplements" },
    why: [
      "A nearly full ring creates a gap people want to close, which makes them look twice.",
      "Naming the day makes a routine feel concrete rather than a vague promise.",
      "Keep it to the routine itself and never imply a medical result.",
    ],
    headline: "Almost at day 30",
    primary: "A simple 30-day routine, one small step a day. No health claims: describe the habit only.",
  },
  {
    id: "mirror-note", type: "static", trending: true,
    category: "Beauty & Skincare", label: "Beauty & Skincare", title: "Foggy Mirror Day Log",
    format: "4:5 · Static · Handwritten on a steamed mirror", framework: "Habit",
    art: { kind: "quote", bg: "linear-gradient(160deg,#fef3c7 0%,#fde68a 100%)", hl: "#92400e", hook: "Small *daily* proof", text: "day 3: calm skin", sign: "Evening routine", tag: "Skincare" },
    why: [
      "A handwritten note feels like a private diary line, not an ad.",
      "A specific day count makes the result feel earned and believable.",
      "Keep the line to what customers really report, and never promise a cure.",
    ],
    headline: "Day 3: calm skin",
    primary: "A simple evening routine for calmer-looking skin. Use only what your own customers genuinely say.",
  },
  {
    id: "search-bar-flight", type: "static", trending: true,
    category: "Travel", label: "Travel", title: "Search Bar Intent",
    format: "4:5 · Static · Phone search on a cafe table", framework: "Intent",
    art: { kind: "offer", bg: "linear-gradient(160deg,#0f766e 0%,#134e4a 100%)", hl: "#99f6e4", hook: "You were *already* searching", big: "€89", sub: "Athens · direct · 3h 20m", pills: ["Direct flight","October dates"], cta: "See flights", tag: "Travel" },
    why: [
      "It mirrors the exact search the viewer has typed themselves, so it feels personal.",
      "A real price and flight time answer the question before they tap.",
      "Always show a fare you can actually book and the date it applies to.",
    ],
    headline: "Cheap flights to Athens in October",
    primary: "Direct flights from €89. Check availability and show the travel dates in the ad.",
  },
  {
    id: "gift-chat-hoodie", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Gift Chat Reply",
    format: "4:5 · Static · iMessage thread beside a wrapped hoodie", framework: "Social Proof",
    art: { kind: "quote", bg: "linear-gradient(160deg,#292524 0%,#0c0a09 100%)", hl: "#fcd34d", hook: "The *easy* gift answer", text: "a hoodie. a good one", sign: "Ordered.", tag: "Gift idea" },
    why: [
      "A text thread shows the buying decision as a two-line conversation.",
      "The wrapped plain hoodie tells people it is ready to give.",
      "Works best near a gifting date, so tie it to a real deadline.",
    ],
    headline: "A hoodie. A good one.",
    primary: "A plain, well-made black hoodie that gifts easily. Add your delivery cut-off before the holiday.",
  },
  {
    id: "desk-vitamin", type: "static", trending: true,
    category: "Supplements", label: "Supplements", title: "Office Desk Vitamin",
    format: "4:5 · Static · Lifestyle photo", framework: "Routine",
    art: { kind: "quote", bg: "linear-gradient(160deg,#f1f5f9 0%,#cbd5e1 100%)", hl: "#1d4ed8", hook: "Part of the *workday*", text: "Daily Focus", sign: "One capsule with water", tag: "Supplements" },
    why: [
      "A real person at a real desk makes the product feel like part of a normal day.",
      "The capsule moment shows how it is used, so there is nothing to work out.",
      "Keep claims to the routine itself, never to medical results.",
    ],
    headline: "Part of the workday",
    primary: "One capsule with your morning water. Show the routine and avoid health claims.",
  },
  {
    id: "track-sneaker", type: "static", trending: true,
    category: "Sport & Fitness", label: "Sport & Fitness", title: "Running Shoe Track Hero",
    format: "4:5 · Static · Product on location", framework: "Context",
    art: { kind: "offer", bg: "linear-gradient(160deg,#9a3412 0%,#431407 100%)", hl: "#fed7aa", hook: "Built for the *track*", big: "NEW", sub: "cushioned running shoe", pills: ["Cushioned","Breathable mesh"], cta: "Shop now", tag: "Running" },
    why: [
      "Placing the shoe on the track tells people what it is for before any words do.",
      "Low angle and a blurred runner add motion without hiding the product.",
      "Replace the demo shoe with the client product shot at the same height.",
    ],
    headline: "Built for the track",
    primary: "A cushioned running shoe with breathable mesh. Add the real weight and sizes.",
  },
  {
    id: "ac-summer", type: "static", trending: true,
    category: "Local Services", label: "Local Services", title: "AC Repair Summer",
    format: "4:5 · Static · Technician at work", framework: "Trust",
    art: { kind: "offer", bg: "linear-gradient(160deg,#1e3a8a 0%,#0f172a 100%)", hl: "#bfdbfe", hook: "Before the *heatwave*", big: "24h", sub: "same-day AC repair", pills: ["Free quote","Local team"], cta: "Book a visit", tag: "AC repair" },
    why: [
      "A technician working on a real unit proves the service is real, which a stock icon cannot.",
      "Summer timing creates urgency without a fake countdown.",
      "Only promise a response time you can keep.",
    ],
    headline: "Before the heatwave",
    primary: "Same-day AC repair from a local team. Add your real response time and area.",
  },
  {
    id: "pc-studio", type: "static", trending: true,
    category: "Electronics", label: "Electronics", title: "Prebuilt PC Studio Catalog",
    format: "4:5 · Static · Studio catalog shot", framework: "Clarity",
    art: { kind: "offer", bg: "linear-gradient(160deg,#334155 0%,#0f172a 100%)", hl: "#c7d2fe", hook: "Ready to *plug in*", big: "PC", sub: "built, tested, shipped", pills: ["Tested","1-year warranty"], cta: "See builds", tag: "Prebuilt PC" },
    why: [
      "A clean pedestal shot makes the product look like a catalog item people can trust.",
      "Visible internals show the quality without a spec table.",
      "Add specs and warranty terms in the copy, not the picture.",
    ],
    headline: "Ready to plug in",
    primary: "A prebuilt PC that is built, tested and shipped. Add the real specs and warranty.",
  },
  {
    id: "scandi-chair", type: "static", trending: true,
    category: "Home & Decor", label: "Home & Decor", title: "Scandi Wishbone UGC",
    format: "4:5 · Static · Calm interior", framework: "Aspiration",
    art: { kind: "quote", bg: "linear-gradient(160deg,#f5f5f4 0%,#d6d3d1 100%)", hl: "#44403c", hook: "A *calmer* corner", text: "Slow mornings", sign: "Solid oak, hand finished", tag: "Furniture" },
    why: [
      "A styled corner sells the feeling of the room, not just the chair.",
      "Soft light and plain walls make it look like a home photo, not an ad.",
      "Say the material and finish so the calm look has a fact behind it.",
    ],
    headline: "A calmer corner",
    primary: "A solid wood chair for slow mornings. Name the wood and finish.",
  },
  {
    id: "loft-sweatshirt", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Warehouse Loft Fashion",
    format: "4:5 · Static · Lifestyle portrait", framework: "Identity",
    art: { kind: "quote", bg: "linear-gradient(160deg,#9a3412 0%,#431407 100%)", hl: "#fed7aa", hook: "Easy *everyday* fit", text: "Oversized, soft, plain", sign: "Heavyweight cotton", tag: "Fashion" },
    why: [
      "Warm light and an industrial space give a plain garment a point of view.",
      "A relaxed smile reads as real, not posed.",
      "Swap in your own plain piece, and keep any print or logo clear.",
    ],
    headline: "Easy everyday fit",
    primary: "An oversized crewneck in heavyweight cotton. Add sizes and care details.",
  },
  {
    id: "lavender-scent", type: "static", trending: true,
    category: "Beauty & Skincare", label: "Beauty & Skincare", title: "Lavender Field Scent",
    format: "4:5 · Static · Hand-held product", framework: "Sensory",
    art: { kind: "quote", bg: "linear-gradient(160deg,#ede9fe 0%,#c4b5fd 100%)", hl: "#5b21b6", hook: "Smells like *a field*", text: "Lavender Balm", sign: "Soothing daily balm", tag: "Skincare" },
    why: [
      "The flower field makes the scent visible, which is hard to do in a still ad.",
      "A hand holding the tube shows size and texture honestly.",
      "Mention only what the formula really contains.",
    ],
    headline: "Smells like a field",
    primary: "A soothing daily balm with a lavender scent. List the real ingredients.",
  },
  {
    id: "berry-splash", type: "static", trending: true,
    category: "Food & Bev", label: "Food & Beverages", title: "Berry Purple Splash",
    format: "4:5 · Static · Product splash hero", framework: "Stop-rate",
    art: { kind: "offer", bg: "linear-gradient(160deg,#581c87 0%,#2e1065 100%)", hl: "#e9d5ff", hook: "Taste the *splash*", big: "BERRY", sub: "sparkling juice · 330ml", pills: ["Naturally flavoured","Zero fuss"], cta: "Shop now", tag: "Drinks" },
    why: [
      "Bold colour and a frozen splash stop the thumb faster than a calm shelf shot.",
      "One strong colour makes the flavour obvious in half a second.",
      "Keep the flavour name large and the claims small and true.",
    ],
    headline: "Taste the splash",
    primary: "A sparkling juice with a berry kick. Check flavour and ingredient claims.",
  },
  {
    id: "fragrance-portrait", type: "static", trending: true,
    category: "Fragrances", label: "Fragrances", title: "Dramatic Fragrance Portrait",
    format: "4:5 · Static · Studio portrait", framework: "Mood",
    art: { kind: "quote", bg: "linear-gradient(160deg,#1c1917 0%,#0c0a09 100%)", hl: "#fcd34d", hook: "One *look*", text: "Amber, woods, smoke", sign: "Eau de parfum", tag: "Fragrance" },
    why: [
      "Hiding half the face behind the bottle makes the bottle the story.",
      "Low-key light and a dark background feel premium without extra words.",
      "Name the notes in the copy and let the picture carry the mood.",
    ],
    headline: "One look",
    primary: "An amber, woody eau de parfum. Add the real notes and size.",
  },
  {
    id: "hotel-pool", type: "static", trending: true,
    category: "Travel", label: "Travel", title: "Design Hotel Pool Shadows",
    format: "4:5 · Static · Place photo", framework: "Aspiration",
    art: { kind: "offer", bg: "linear-gradient(160deg,#92400e 0%,#451a03 100%)", hl: "#fde68a", hook: "Your quiet *escape*", big: "3 nights", sub: "design hotel · courtyard pool", pills: ["Breakfast included","Free cancellation"], cta: "Check dates", tag: "Hotel" },
    why: [
      "Long afternoon shadows make the place feel calm and expensive at the same time.",
      "No people lets the viewer put themselves in the scene.",
      "Show a real price and dates alongside the photo.",
    ],
    headline: "Your quiet escape",
    primary: "A design hotel with a courtyard pool. Add your real rates and dates.",
  },
  {
    id: "knit-stack", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Boutique Knit Stack",
    format: "4:5 · Static · In-store product", framework: "Context",
    art: { kind: "quote", bg: "linear-gradient(160deg,#f5f0e8 0%,#d6c9b4 100%)", hl: "#78350f", hook: "Soft enough to *live in*", text: "Chunky knit", sign: "Three neutral shades", tag: "Knitwear" },
    why: [
      "A stack on a real boutique shelf shows the texture and colour range in one look.",
      "Window light makes the wool look soft without any claim written on it.",
      "Name the fibre and sizes in the copy, since the picture can only show the feel.",
    ],
    headline: "Soft enough to live in",
    primary: "Chunky knit sweaters in three neutral shades. Add the fibre blend, sizes and care.",
  },
  {
    id: "hoodie-street", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Black Hoodie Street Walk",
    format: "4:5 · Static · Lifestyle, back view", framework: "Identity",
    art: { kind: "quote", bg: "linear-gradient(160deg,#1c1917 0%,#0c0a09 100%)", hl: "#fcd34d", hook: "Your *everyday* black", text: "Oversized hoodie", sign: "Heavyweight cotton", tag: "Streetwear" },
    why: [
      "A back view at golden hour gives a plain hoodie a mood without needing a face.",
      "The street setting shows where it is worn, which sells the lifestyle.",
      "Plain garment keeps the fit and colour as the only message.",
    ],
    headline: "Your everyday black",
    primary: "An oversized black hoodie in heavyweight cotton. Add sizes and fabric weight.",
  },
  {
    id: "capsule-flatlay", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Capsule Outfit Flat Lay",
    format: "4:5 · Static · Flat lay", framework: "Clarity",
    art: { kind: "offer", bg: "linear-gradient(160deg,#f1f5f9 0%,#cbd5e1 100%)", hl: "#1d4ed8", hook: "A full look, *five* pieces", big: "5", sub: "pieces, one outfit", pills: ["Mix and match","Free returns"], cta: "Shop the look", tag: "Capsule" },
    why: [
      "Seeing the whole outfit from above answers what goes with what.",
      "Neutral linen keeps attention on the pieces, not the background.",
      "Say how many pieces and what the return terms are.",
    ],
    headline: "A full look in five pieces",
    primary: "A simple outfit you can wear this week. Add the real pieces and return terms.",
  },
  {
    id: "denim-crate", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Denim Stack on Crate",
    format: "4:5 · Static · In-store product", framework: "Context",
    art: { kind: "offer", bg: "linear-gradient(160deg,#1e3a8a 0%,#0f172a 100%)", hl: "#bfdbfe", hook: "Find your *wash*", big: "3", sub: "washes, one great fit", pills: ["Straight leg","True to size"], cta: "Shop denim", tag: "Denim" },
    why: [
      "Stacked washes let people pick a shade at a glance.",
      "A rustic crate tells the story of a shop, not a catalogue.",
      "Add the fit name and size range, since that is the real decision.",
    ],
    headline: "Find your wash",
    primary: "Straight-leg denim in indigo and washed black. Add sizes and inseam lengths.",
  },
  {
    id: "linen-hanger", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Linen Shirt on Wall",
    format: "4:5 · Static · Product on location", framework: "Sensory",
    art: { kind: "quote", bg: "linear-gradient(160deg,#fafaf9 0%,#e7e5e4 100%)", hl: "#44403c", hook: "Made for *warm* days", text: "Washed linen", sign: "Breathable, relaxed fit", tag: "Linen" },
    why: [
      "Hanging on a sunlit wall shows how light the fabric is.",
      "Soft shadow and plaster texture feel calm and premium.",
      "Only claim breathability if the fabric is genuinely linen.",
    ],
    headline: "Made for warm days",
    primary: "A washed linen shirt with a relaxed fit. Add sizes and care instructions.",
  },
  {
    id: "tote-market", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Canvas Tote at the Market",
    format: "4:5 · Static · Lifestyle product", framework: "Context",
    art: { kind: "quote", bg: "linear-gradient(160deg,#fef3c7 0%,#fcd34d 100%)", hl: "#78350f", hook: "Carries your *whole* day", text: "Canvas tote", sign: "Heavy cotton, deep pockets", tag: "Accessories" },
    why: [
      "A bag with real shopping in it shows how much it holds better than a size chart.",
      "Sunny market light feels everyday and easy, not staged.",
      "State the capacity and strap drop in the copy.",
    ],
    headline: "Carries your whole day",
    primary: "A heavy canvas tote with deep pockets. Add capacity, strap drop and care.",
  },
  {
    id: "trench-rain", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Trench Coat in the Rain",
    format: "4:5 · Static · Lifestyle, back view", framework: "Mood",
    art: { kind: "quote", bg: "linear-gradient(160deg,#1e293b 0%,#0f172a 100%)", hl: "#fde68a", hook: "Made for *grey* days", text: "The classic trench", sign: "Water-resistant cotton", tag: "Outerwear" },
    why: [
      "Rain and warm shop lights prove the coat works in bad weather, which is the buying reason.",
      "Back view keeps attention on the cut and colour.",
      "Only say water-resistant if the fabric is tested.",
    ],
    headline: "Made for grey days",
    primary: "A classic beige trench in water-resistant cotton. Add sizes and the real fabric details.",
  },
  {
    id: "caps-wall", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Cap Colour Lineup",
    format: "4:5 · Static · Colour lineup", framework: "Stop-rate",
    art: { kind: "offer", bg: "linear-gradient(160deg,#fbcfe8 0%,#f472b6 100%)", hl: "#831843", hook: "Pick your *shade*", big: "5", sub: "colours, one fit", pills: ["Adjustable","Cotton twill"], cta: "Shop caps", tag: "Caps" },
    why: [
      "Five colours in a row let people choose in one glance.",
      "A bold pastel wall stops the scroll without any text.",
      "Name the fabric and fit so the colours are not the only reason to buy.",
    ],
    headline: "Pick your shade",
    primary: "Plain cotton twill caps in five colours. Add the fit and sizing details.",
  },
  {
    id: "snow-bench-knits", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Snow Bench Winter Knits",
    format: "4:5 · Static · Seasonal scene", framework: "Context",
    art: { kind: "quote", bg: "linear-gradient(160deg,#f1f5f9 0%,#cbd5e1 100%)", hl: "#1e293b", hook: "Cold day? *Sorted.*", text: "Beanie and scarf set", sign: "Soft wool blend", tag: "Winter" },
    why: [
      "A knit set on a frosted bench makes the cold and the cosy obvious at once.",
      "Natural neutrals keep the product the focus against the white snow.",
      "Name the fibre blend so warmth has a fact behind it.",
    ],
    headline: "Cold day? Sorted.",
    primary: "A soft knit beanie and scarf set. Add the fibre blend, colours and care.",
  },
  {
    id: "loafers-terrace", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Leather Loafers on the Terrace",
    format: "4:5 · Static · Product on location", framework: "Aspiration",
    art: { kind: "offer", bg: "linear-gradient(160deg,#ffedd5 0%,#fdba74 100%)", hl: "#7c2d12", hook: "Made for *slow* summers", big: "LEATHER", sub: "tan leather loafers", pills: ["Soft leather","Cushioned insole"], cta: "Shop loafers", tag: "Footwear" },
    why: [
      "A sea view and warm stone make the shoes feel like part of the holiday.",
      "The pair sits centred and sharp, so the shape and stitching are easy to judge.",
      "Add sizes and the leather type to answer the first buyer question.",
    ],
    headline: "Made for slow summers",
    primary: "Tan leather loafers with a cushioned insole. Add sizes and leather details.",
  },
  {
    id: "blazer-library", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Navy Blazer in the Library",
    format: "4:5 · Static · Lifestyle still life", framework: "Aspiration",
    art: { kind: "quote", bg: "linear-gradient(160deg,#e2e8f0 0%,#94a3b8 100%)", hl: "#0f172a", hook: "Dress for *the room*", text: "The navy blazer", sign: "Wool-blend, tailored fit", tag: "Tailoring" },
    why: [
      "A blazer draped over a velvet chair signals polish without a model.",
      "Warm wood and lamp light give a premium, quiet mood.",
      "Mention the cloth, the fit and whether it is lined.",
    ],
    headline: "Dress for the room",
    primary: "A tailored navy wool-blend blazer. Add sizes, lining and care.",
  },
  {
    id: "rooftop-friends-tees", type: "static", trending: true,
    category: "Fashion", label: "Fashion", title: "Rooftop Friends in White Tees",
    format: "4:5 · Static · UGC lifestyle", framework: "Social proof",
    art: { kind: "quote", bg: "linear-gradient(160deg,#fff7ed 0%,#fed7aa 100%)", hl: "#9a3412", hook: "Your *everyday* tee", text: "The perfect white tee", sign: "Heavyweight cotton", tag: "Basics" },
    why: [
      "Real laughter on a rooftop looks like a moment, not an ad, so it earns attention.",
      "Two people in the same plain tee shows the fit on different bodies.",
      "Say the cotton weight and the sizes so the feeling turns into a purchase.",
    ],
    headline: "Your everyday tee",
    primary: "A heavyweight cotton white tee. Add the fabric weight and size range.",
  },
];

const SAMPLES = [
  {
    id: "skin", label: "Skincare Serum – Low ROAS", brand: "Lumen Glow", type: "static",
    headline: "Glowing skin starts with vitamin C",
    copy: "Dull skin? Our vitamin C serum evens tone in 4 weeks, with 15% L-ascorbic acid. Apply two drops each morning under your SPF. Free shipping on every order. Shop at lumenglow.com.",
  },
  {
    id: "gym", label: "Gym Supplement – High CPA", brand: "IronPeak", type: "video",
    headline: "Best pre-workout on the market",
    copy: "IronPeak Pre-Workout has 300mg of caffeine and 6g of citrulline per scoop. Available in 5 flavors. Buy it on our site.",
  },
  {
    id: "apparel", label: "E-com Apparel – Low Clicks", brand: "Nordvik", type: "static",
    headline: "New fall collection is here",
    copy: "Check out our latest styles for fall. Comfortable, stylish and made to last. Free shipping on orders over $75.",
  },
];

export { LOGO_SRC, CATEGORIES, TEMPLATES, SAMPLES };
